import type { Metadata } from "next";
import { unstable_setRequestLocale } from 'next-intl/server';
import ResponsiveAppBar from "@/component/layout/Appbar";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import Footer from "@/component/layout/Footer";
import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";

export const metadata: Metadata = {
  title: "NextJs Project Template",
  description: "Generated by create next app",
};

const locales = ['en', 'th'];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}

) {

  unstable_setRequestLocale(locale);

  return (
    <html suppressHydrationWarning lang={locale}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ResponsiveAppBar />
              {children}
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
